### ISSUE TITLE
Receive Video Call Crash in Samsung Android 5

### ISSUE THREAD

**Issue by robert589** [voximplant/react-native-voximplant#93]
>  E/AndroidRuntime: FATAL EXCEPTION: EglRenderer
    java.lang.RuntimeException: glCreateShader() failed. GLES20 error: 0
        at org.webrtc.GlShader.compileShader(GlShader.java:24)
        at org.webrtc.GlShader.<init>(GlShader.java:42)
        at org.webrtc.GlGenericDrawer.createShader(GlGenericDrawer.java:153)
        at org.webrtc.GlGenericDrawer.prepareShader(GlGenericDrawer.java:230)
        at org.webrtc.GlGenericDrawer.drawOes(GlGenericDrawer.java:163)
        at org.webrtc.GlRectDrawer.drawOes(GlRectDrawer.java:16)
        at org.webrtc.VideoFrameDrawer.drawTexture(VideoFrameDrawer.java:42)
        at org.webrtc.VideoFrameDrawer.drawFrame(VideoFrameDrawer.java:219)
        at org.webrtc.EglRenderer.renderFrameOnRenderThread(EglRenderer.java:655)
        at org.webrtc.EglRenderer.lambda$vWDJEj1GWjHSjwoQQjEEK_IVOJE(EglRenderer.java)
        at org.webrtc.-$$Lambda$EglRenderer$vWDJEj1GWjHSjwoQQjEEK_IVOJE.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:100)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)

This only happens in one of our phone and the voice call actually works. I think have some problems in the videoview, pls take a look

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reaching out to us!

Could you please provide the information about Voximplant React Native SDK version the issue is reproducible with?

Best regards,
Yulia Grigorieva
